AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'
  Severity: warning

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  CountComments: false
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 40

Metrics/ModuleLength:
  Max: 100

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 7

Rails:
  Enabled: true

# used in the test and for Rails 5
Rails/HttpPositionalArguments:
    Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/rails_admin/bootstrap-sass.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'




# our style changes: disabling style rules we aren't interested in
Style/AlignHash:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundAccessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IndentationConsistency:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MethodCallParentheses:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RescueModifier:
  Severity: warning
Style/SignalException:
  Enabled: false
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/SpaceAfterColon:
  Enabled: false
Style/SpaceAfterComma:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/TrailingBlankLines:
  Enabled: false
Style/TrailingWhitespace:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
