# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###

$ ->
  $('.geocoding_fulladdress').geocomplete
    details: '.geo-details'
    detailsAttribute: 'geocoding'
  $('#find').click ->
    $('#location').trigger 'geocode'
    return
  return

# ---
# generated by js2coffee 2.1.0
