# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55687ccb8de5b7e31a426ab571a08749337cf34e091b810a47119d3311d2c8970377517e36f4e971060f38f1c84ccf10e5017a40af96a8933774776e732b039b
  stripe_publishable_key: pk_test_fyRNOLDgwu4DCReP9newgTsF
  stripe_secret_key: sk_test_xN87cqvjUz09casHquCDsp62
  stripe_client_id: ca_8HluGk4i9JWdkCpktFTeQftbHXTByTxn

test:
  secret_key_base: 51b8c31c6bc695ddd0ecf1f4ebea5d8fa42b410ac6c1058e3d0c8ff172a4f4030bb7420cd629cb3974067341c499dc7ed34fa1f03b90901be062e2bc4df2a24d
  stripe_publishable_key: pk_test_fyRNOLDgwu4DCReP9newgTsF
  stripe_secret_key: sk_test_xN87cqvjUz09casHquCDsp62
  stripe_client_id: ca_8HluGk4i9JWdkCpktFTeQftbHXTByTxn

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>





