# link to all class="alert"
# and close automatiquely the alert box
# example of association:
# <div class="alert alert-success alert-block">
#<button type="button" class="close" data-dismiss="alert">&times;</button>
#        <h4>Success!</h4>
#        This is working great !
# </div>
$(document).on 'turbolinks:load', ->
  window.setTimeout (->
    $('.alert').fadeTo(500, 0).slideUp 500, ->
      $(this).remove()
      return
    return
  ), 4000
  return

# ---
# generated by js2coffee 2.2.0