require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ForumFamiliesController, type: :controller do

  # even if not recommended, we test the rendering in the controller
  render_views

  before do
    @forum_family = forum_families(:one)
  end

  # This should return the minimal set of attributes required to create a valid
  # ForumFamily. As you add validations to ForumFamily, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForumFamiliesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all forum_families as @forum_families" do
      forum_family = ForumFamily.all
      get :index, params: {}, session: valid_session
      expect(assigns(:forum_families)).not_to be_nil
    end
  end

  describe "GET #show" do
    it "assigns the requested forum_family as @forum_family" do
      get :show, id: @forum_family.to_param, session: valid_session
      expect(assigns(:forum_family)).to eq(@forum_family)
    end
  end

  describe "POST #sort" do
    it 'sort families if logged' do
      assert(families(:one).position == 1)
      assert(families(:two).position == 2)
      # add a signed employee to perform the tests
      sign_in(employees(:one), scope: :employee)

      # assert_equal(@order_one.position, 2) do
      post :sort, locale: I18n.default_locale, 'family' => [families(:two).id.to_s, families(:one).id.to_s] do
        assert(families(:one).position == 2)
        assert(families(:two).position == 1)
      end
      # we Need assigns to recover the modifications from the Controller
      # end

      expect(response).to be_success
    end

    it 'not sort families if not logged' do
      assert(families(:one).position == 1)
      assert(families(:two).position == 2)
      # add a signed employee to perform the tests
      sign_in(employees(:one), scope: :employee)
      sign_out(:employee)

      # assert_equal(@order_one.position, 2) do
      post :sort, locale: I18n.default_locale, 'family' => [families(:two).id.to_s, families(:one).id.to_s]
      # we Need assigns to recover the modifications from the Controller
      # end

      expect(response).to have_http_status(302)
    end
  end

end
