require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StripeAccountsController, type: :controller do

  # even if not recommended, we test the rendering in the controller
  render_views

  before do
    @customer = customers(:one)
    @request.env['user_mailer.mapping'] = Devise.mappings[:customer]
    # get :new
  end

  # This should return the minimal set of attributes required to create a valid
  # StripeAccount. As you add validations to StripeAccount, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StripeAccountsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #standalone" do
    it 'redirect to customer for standalone' do
      sign_in(@customer, scope: :customer)
      get :standalone
      expect(response).to redirect_to(customer_path(@customer))
    end
  end

end
